# ... existing imports ...

DEFAULT_GLOSS = [
    # ... existing glosses ...
    "fingerspell_y",
    # ... other glosses ...
]

# ... existing code ...

def gloss_to_sentence(gloss: str) -> str:
    """Convert gloss to a natural language sentence."""
    gloss_map = {
        # ... existing mappings ...
        "fingerspell_y": "The letter Y",
        # ... other mappings ...
    }
    return gloss_map.get(gloss, gloss)